// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auction_history.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuctionHistory = `-- name: CreateAuctionHistory :one
INSERT INTO auction_history (
    auction_id,
    user_id,
    event,
    amount,
    note
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, auction_id, user_id, event, amount, note, created_at
`

type CreateAuctionHistoryParams struct {
	AuctionID pgtype.UUID  `json:"auction_id"`
	UserID    pgtype.UUID  `json:"user_id"`
	Event     AuctionEvent `json:"event"`
	Amount    pgtype.Int4  `json:"amount"`
	Note      pgtype.Text  `json:"note"`
}

func (q *Queries) CreateAuctionHistory(ctx context.Context, arg CreateAuctionHistoryParams) (AuctionHistory, error) {
	row := q.db.QueryRow(ctx, createAuctionHistory,
		arg.AuctionID,
		arg.UserID,
		arg.Event,
		arg.Amount,
		arg.Note,
	)
	var i AuctionHistory
	err := row.Scan(
		&i.ID,
		&i.AuctionID,
		&i.UserID,
		&i.Event,
		&i.Amount,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const getAuctionHistory = `-- name: GetAuctionHistory :many
SELECT id, auction_id, user_id, event, amount, note, created_at FROM auction_history
WHERE auction_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetAuctionHistory(ctx context.Context, auctionID pgtype.UUID) ([]AuctionHistory, error) {
	rows, err := q.db.Query(ctx, getAuctionHistory, auctionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuctionHistory
	for rows.Next() {
		var i AuctionHistory
		if err := rows.Scan(
			&i.ID,
			&i.AuctionID,
			&i.UserID,
			&i.Event,
			&i.Amount,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuctionHistoryByEvent = `-- name: GetAuctionHistoryByEvent :many

SELECT id, auction_id, user_id, event, amount, note, created_at FROM auction_history
WHERE auction_id = $1
  AND event      = $2
ORDER BY created_at ASC
`

type GetAuctionHistoryByEventParams struct {
	AuctionID pgtype.UUID  `json:"auction_id"`
	Event     AuctionEvent `json:"event"`
}

// full timeline of everything that happened
func (q *Queries) GetAuctionHistoryByEvent(ctx context.Context, arg GetAuctionHistoryByEventParams) ([]AuctionHistory, error) {
	rows, err := q.db.Query(ctx, getAuctionHistoryByEvent, arg.AuctionID, arg.Event)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuctionHistory
	for rows.Next() {
		var i AuctionHistory
		if err := rows.Scan(
			&i.ID,
			&i.AuctionID,
			&i.UserID,
			&i.Event,
			&i.Amount,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserBidHistory = `-- name: GetUserBidHistory :many
SELECT
    ah.id, ah.auction_id, ah.user_id, ah.event, ah.amount, ah.note, ah.created_at,
    a.title        AS auction_title,
    a.current_price AS auction_current_price
FROM auction_history ah
JOIN auctions a ON a.id = ah.auction_id
WHERE ah.user_id = $1
  AND ah.event   IN ('BidPlaced', 'BidIncreased', 'BidRefunded')
ORDER BY ah.created_at DESC
`

type GetUserBidHistoryRow struct {
	ID                  pgtype.UUID        `json:"id"`
	AuctionID           pgtype.UUID        `json:"auction_id"`
	UserID              pgtype.UUID        `json:"user_id"`
	Event               AuctionEvent       `json:"event"`
	Amount              pgtype.Int4        `json:"amount"`
	Note                pgtype.Text        `json:"note"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	AuctionTitle        string             `json:"auction_title"`
	AuctionCurrentPrice int32              `json:"auction_current_price"`
}

func (q *Queries) GetUserBidHistory(ctx context.Context, userID pgtype.UUID) ([]GetUserBidHistoryRow, error) {
	rows, err := q.db.Query(ctx, getUserBidHistory, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserBidHistoryRow
	for rows.Next() {
		var i GetUserBidHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.AuctionID,
			&i.UserID,
			&i.Event,
			&i.Amount,
			&i.Note,
			&i.CreatedAt,
			&i.AuctionTitle,
			&i.AuctionCurrentPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
