// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auctions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelAuction = `-- name: CancelAuction :one
UPDATE auctions
SET
    status     = 'Cancelled',
    updated_at = NOW()
WHERE id        = $1
  AND seller_id = $2
  AND status    = 'Scheduled'
RETURNING id, seller_id, current_bidder_id, title, description, type, status, starting_price, reserved_price, current_price, drop_amount, drop_interval, last_drop_time, extend_on_bid, extend_minutes, start_time, end_time, original_end_time, created_at, updated_at
`

type CancelAuctionParams struct {
	ID       pgtype.UUID `json:"id"`
	SellerID pgtype.UUID `json:"seller_id"`
}

// only seller can cancel their own auction
// can only cancel before it starts
func (q *Queries) CancelAuction(ctx context.Context, arg CancelAuctionParams) (Auction, error) {
	row := q.db.QueryRow(ctx, cancelAuction, arg.ID, arg.SellerID)
	var i Auction
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.CurrentBidderID,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.Status,
		&i.StartingPrice,
		&i.ReservedPrice,
		&i.CurrentPrice,
		&i.DropAmount,
		&i.DropInterval,
		&i.LastDropTime,
		&i.ExtendOnBid,
		&i.ExtendMinutes,
		&i.StartTime,
		&i.EndTime,
		&i.OriginalEndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countAuctionsList = `-- name: CountAuctionsList :one
SELECT COUNT(*) FROM auctions
WHERE
    ($1::text = '' OR type::text   = $1) AND
    ($2::text = '' OR status::text = $2)
`

type CountAuctionsListParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
}

func (q *Queries) CountAuctionsList(ctx context.Context, arg CountAuctionsListParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuctionsList, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuction = `-- name: CreateAuction :one
INSERT INTO auctions (
    seller_id,
    title,
    description,
    type,
    starting_price,
    reserved_price,
    current_price,
    drop_amount,
    drop_interval,
    extend_on_bid,
    extend_minutes,
    start_time,
    end_time,
    original_end_time
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $13)
RETURNING id, seller_id, current_bidder_id, title, description, type, status, starting_price, reserved_price, current_price, drop_amount, drop_interval, last_drop_time, extend_on_bid, extend_minutes, start_time, end_time, original_end_time, created_at, updated_at
`

type CreateAuctionParams struct {
	SellerID      pgtype.UUID        `json:"seller_id"`
	Title         string             `json:"title"`
	Description   string             `json:"description"`
	Type          AuctionType        `json:"type"`
	StartingPrice int32              `json:"starting_price"`
	ReservedPrice int32              `json:"reserved_price"`
	CurrentPrice  int32              `json:"current_price"`
	DropAmount    pgtype.Int4        `json:"drop_amount"`
	DropInterval  pgtype.Int4        `json:"drop_interval"`
	ExtendOnBid   bool               `json:"extend_on_bid"`
	ExtendMinutes int32              `json:"extend_minutes"`
	StartTime     pgtype.Timestamptz `json:"start_time"`
	EndTime       pgtype.Timestamptz `json:"end_time"`
}

// original_end_time = end_time at creation
func (q *Queries) CreateAuction(ctx context.Context, arg CreateAuctionParams) (Auction, error) {
	row := q.db.QueryRow(ctx, createAuction,
		arg.SellerID,
		arg.Title,
		arg.Description,
		arg.Type,
		arg.StartingPrice,
		arg.ReservedPrice,
		arg.CurrentPrice,
		arg.DropAmount,
		arg.DropInterval,
		arg.ExtendOnBid,
		arg.ExtendMinutes,
		arg.StartTime,
		arg.EndTime,
	)
	var i Auction
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.CurrentBidderID,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.Status,
		&i.StartingPrice,
		&i.ReservedPrice,
		&i.CurrentPrice,
		&i.DropAmount,
		&i.DropInterval,
		&i.LastDropTime,
		&i.ExtendOnBid,
		&i.ExtendMinutes,
		&i.StartTime,
		&i.EndTime,
		&i.OriginalEndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const dropDutchPrice = `-- name: DropDutchPrice :one

UPDATE auctions
SET
    current_price  = current_price - drop_amount,
    last_drop_time = NOW(),
    updated_at     = NOW()
WHERE id           = $1
  AND current_price > drop_amount
RETURNING id, seller_id, current_bidder_id, title, description, type, status, starting_price, reserved_price, current_price, drop_amount, drop_interval, last_drop_time, extend_on_bid, extend_minutes, start_time, end_time, original_end_time, created_at, updated_at
`

// $1 = extend_minutes from auction row
// safety — never drop below zero
func (q *Queries) DropDutchPrice(ctx context.Context, id pgtype.UUID) (Auction, error) {
	row := q.db.QueryRow(ctx, dropDutchPrice, id)
	var i Auction
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.CurrentBidderID,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.Status,
		&i.StartingPrice,
		&i.ReservedPrice,
		&i.CurrentPrice,
		&i.DropAmount,
		&i.DropInterval,
		&i.LastDropTime,
		&i.ExtendOnBid,
		&i.ExtendMinutes,
		&i.StartTime,
		&i.EndTime,
		&i.OriginalEndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const extendAuctionEndTime = `-- name: ExtendAuctionEndTime :one
UPDATE auctions
SET
    end_time   = end_time + ($1 * INTERVAL '1 minute'),
    updated_at = NOW()
WHERE id = $2
RETURNING id, seller_id, current_bidder_id, title, description, type, status, starting_price, reserved_price, current_price, drop_amount, drop_interval, last_drop_time, extend_on_bid, extend_minutes, start_time, end_time, original_end_time, created_at, updated_at
`

type ExtendAuctionEndTimeParams struct {
	Column1 interface{} `json:"column_1"`
	ID      pgtype.UUID `json:"id"`
}

func (q *Queries) ExtendAuctionEndTime(ctx context.Context, arg ExtendAuctionEndTimeParams) (Auction, error) {
	row := q.db.QueryRow(ctx, extendAuctionEndTime, arg.Column1, arg.ID)
	var i Auction
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.CurrentBidderID,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.Status,
		&i.StartingPrice,
		&i.ReservedPrice,
		&i.CurrentPrice,
		&i.DropAmount,
		&i.DropInterval,
		&i.LastDropTime,
		&i.ExtendOnBid,
		&i.ExtendMinutes,
		&i.StartTime,
		&i.EndTime,
		&i.OriginalEndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveAuctions = `-- name: GetActiveAuctions :many

SELECT id, seller_id, current_bidder_id, title, description, type, status, starting_price, reserved_price, current_price, drop_amount, drop_interval, last_drop_time, extend_on_bid, extend_minutes, start_time, end_time, original_end_time, created_at, updated_at FROM auctions
WHERE status = 'Active'
ORDER BY end_time ASC
`

// always use this inside bid transaction
// never use GetAuctionByID inside transaction
func (q *Queries) GetActiveAuctions(ctx context.Context) ([]Auction, error) {
	rows, err := q.db.Query(ctx, getActiveAuctions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Auction
	for rows.Next() {
		var i Auction
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.CurrentBidderID,
			&i.Title,
			&i.Description,
			&i.Type,
			&i.Status,
			&i.StartingPrice,
			&i.ReservedPrice,
			&i.CurrentPrice,
			&i.DropAmount,
			&i.DropInterval,
			&i.LastDropTime,
			&i.ExtendOnBid,
			&i.ExtendMinutes,
			&i.StartTime,
			&i.EndTime,
			&i.OriginalEndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveDutchAuctions = `-- name: GetActiveDutchAuctions :many

SELECT id, seller_id, current_bidder_id, title, description, type, status, starting_price, reserved_price, current_price, drop_amount, drop_interval, last_drop_time, extend_on_bid, extend_minutes, start_time, end_time, original_end_time, created_at, updated_at FROM auctions
WHERE status = 'Active'
  AND type   = 'Dutch'
`

// scheduler uses this to end auctions
func (q *Queries) GetActiveDutchAuctions(ctx context.Context) ([]Auction, error) {
	rows, err := q.db.Query(ctx, getActiveDutchAuctions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Auction
	for rows.Next() {
		var i Auction
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.CurrentBidderID,
			&i.Title,
			&i.Description,
			&i.Type,
			&i.Status,
			&i.StartingPrice,
			&i.ReservedPrice,
			&i.CurrentPrice,
			&i.DropAmount,
			&i.DropInterval,
			&i.LastDropTime,
			&i.ExtendOnBid,
			&i.ExtendMinutes,
			&i.StartTime,
			&i.EndTime,
			&i.OriginalEndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuctionByID = `-- name: GetAuctionByID :one
SELECT id, seller_id, current_bidder_id, title, description, type, status, starting_price, reserved_price, current_price, drop_amount, drop_interval, last_drop_time, extend_on_bid, extend_minutes, start_time, end_time, original_end_time, created_at, updated_at FROM auctions
WHERE id = $1
`

func (q *Queries) GetAuctionByID(ctx context.Context, id pgtype.UUID) (Auction, error) {
	row := q.db.QueryRow(ctx, getAuctionByID, id)
	var i Auction
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.CurrentBidderID,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.Status,
		&i.StartingPrice,
		&i.ReservedPrice,
		&i.CurrentPrice,
		&i.DropAmount,
		&i.DropInterval,
		&i.LastDropTime,
		&i.ExtendOnBid,
		&i.ExtendMinutes,
		&i.StartTime,
		&i.EndTime,
		&i.OriginalEndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuctionsBySellerID = `-- name: GetAuctionsBySellerID :many
SELECT id, seller_id, current_bidder_id, title, description, type, status, starting_price, reserved_price, current_price, drop_amount, drop_interval, last_drop_time, extend_on_bid, extend_minutes, start_time, end_time, original_end_time, created_at, updated_at FROM auctions
WHERE seller_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetAuctionsBySellerID(ctx context.Context, sellerID pgtype.UUID) ([]Auction, error) {
	rows, err := q.db.Query(ctx, getAuctionsBySellerID, sellerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Auction
	for rows.Next() {
		var i Auction
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.CurrentBidderID,
			&i.Title,
			&i.Description,
			&i.Type,
			&i.Status,
			&i.StartingPrice,
			&i.ReservedPrice,
			&i.CurrentPrice,
			&i.DropAmount,
			&i.DropInterval,
			&i.LastDropTime,
			&i.ExtendOnBid,
			&i.ExtendMinutes,
			&i.StartTime,
			&i.EndTime,
			&i.OriginalEndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuctionsList = `-- name: GetAuctionsList :many
SELECT id, seller_id, current_bidder_id, title, description, type, status, starting_price, reserved_price, current_price, drop_amount, drop_interval, last_drop_time, extend_on_bid, extend_minutes, start_time, end_time, original_end_time, created_at, updated_at FROM auctions
WHERE
    ($1::text = '' OR type::text   = $1) AND
    ($2::text = '' OR status::text = $2)
ORDER BY created_at DESC
LIMIT  $3
OFFSET $4
`

type GetAuctionsListParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) GetAuctionsList(ctx context.Context, arg GetAuctionsListParams) ([]Auction, error) {
	rows, err := q.db.Query(ctx, getAuctionsList,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Auction
	for rows.Next() {
		var i Auction
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.CurrentBidderID,
			&i.Title,
			&i.Description,
			&i.Type,
			&i.Status,
			&i.StartingPrice,
			&i.ReservedPrice,
			&i.CurrentPrice,
			&i.DropAmount,
			&i.DropInterval,
			&i.LastDropTime,
			&i.ExtendOnBid,
			&i.ExtendMinutes,
			&i.StartTime,
			&i.EndTime,
			&i.OriginalEndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpiredActiveAuctions = `-- name: GetExpiredActiveAuctions :many

SELECT id, seller_id, current_bidder_id, title, description, type, status, starting_price, reserved_price, current_price, drop_amount, drop_interval, last_drop_time, extend_on_bid, extend_minutes, start_time, end_time, original_end_time, created_at, updated_at FROM auctions
WHERE status   = 'Active'
  AND end_time < NOW()
`

// scheduler uses this to activate auctions
func (q *Queries) GetExpiredActiveAuctions(ctx context.Context) ([]Auction, error) {
	rows, err := q.db.Query(ctx, getExpiredActiveAuctions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Auction
	for rows.Next() {
		var i Auction
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.CurrentBidderID,
			&i.Title,
			&i.Description,
			&i.Type,
			&i.Status,
			&i.StartingPrice,
			&i.ReservedPrice,
			&i.CurrentPrice,
			&i.DropAmount,
			&i.DropInterval,
			&i.LastDropTime,
			&i.ExtendOnBid,
			&i.ExtendMinutes,
			&i.StartTime,
			&i.EndTime,
			&i.OriginalEndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScheduledAuctionsReadyToStart = `-- name: GetScheduledAuctionsReadyToStart :many
SELECT id, seller_id, current_bidder_id, title, description, type, status, starting_price, reserved_price, current_price, drop_amount, drop_interval, last_drop_time, extend_on_bid, extend_minutes, start_time, end_time, original_end_time, created_at, updated_at FROM auctions
WHERE status     = 'Scheduled'
  AND start_time <= NOW()
`

func (q *Queries) GetScheduledAuctionsReadyToStart(ctx context.Context) ([]Auction, error) {
	rows, err := q.db.Query(ctx, getScheduledAuctionsReadyToStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Auction
	for rows.Next() {
		var i Auction
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.CurrentBidderID,
			&i.Title,
			&i.Description,
			&i.Type,
			&i.Status,
			&i.StartingPrice,
			&i.ReservedPrice,
			&i.CurrentPrice,
			&i.DropAmount,
			&i.DropInterval,
			&i.LastDropTime,
			&i.ExtendOnBid,
			&i.ExtendMinutes,
			&i.StartTime,
			&i.EndTime,
			&i.OriginalEndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAuctionByID = `-- name: LockAuctionByID :one
SELECT id, seller_id, current_bidder_id, title, description, type, status, starting_price, reserved_price, current_price, drop_amount, drop_interval, last_drop_time, extend_on_bid, extend_minutes, start_time, end_time, original_end_time, created_at, updated_at FROM auctions
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockAuctionByID(ctx context.Context, id pgtype.UUID) (Auction, error) {
	row := q.db.QueryRow(ctx, lockAuctionByID, id)
	var i Auction
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.CurrentBidderID,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.Status,
		&i.StartingPrice,
		&i.ReservedPrice,
		&i.CurrentPrice,
		&i.DropAmount,
		&i.DropInterval,
		&i.LastDropTime,
		&i.ExtendOnBid,
		&i.ExtendMinutes,
		&i.StartTime,
		&i.EndTime,
		&i.OriginalEndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAuctionAfterBid = `-- name: UpdateAuctionAfterBid :one

UPDATE auctions
SET
    current_price     = $1,
    current_bidder_id = $2,
    updated_at        = NOW()
WHERE id = $3
RETURNING id, seller_id, current_bidder_id, title, description, type, status, starting_price, reserved_price, current_price, drop_amount, drop_interval, last_drop_time, extend_on_bid, extend_minutes, start_time, end_time, original_end_time, created_at, updated_at
`

type UpdateAuctionAfterBidParams struct {
	CurrentPrice    int32       `json:"current_price"`
	CurrentBidderID pgtype.UUID `json:"current_bidder_id"`
	ID              pgtype.UUID `json:"id"`
}

// scheduler uses this to drop prices
func (q *Queries) UpdateAuctionAfterBid(ctx context.Context, arg UpdateAuctionAfterBidParams) (Auction, error) {
	row := q.db.QueryRow(ctx, updateAuctionAfterBid, arg.CurrentPrice, arg.CurrentBidderID, arg.ID)
	var i Auction
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.CurrentBidderID,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.Status,
		&i.StartingPrice,
		&i.ReservedPrice,
		&i.CurrentPrice,
		&i.DropAmount,
		&i.DropInterval,
		&i.LastDropTime,
		&i.ExtendOnBid,
		&i.ExtendMinutes,
		&i.StartTime,
		&i.EndTime,
		&i.OriginalEndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAuctionStatus = `-- name: UpdateAuctionStatus :one
UPDATE auctions
SET
    status     = $1,
    updated_at = NOW()
WHERE id = $2
RETURNING id, seller_id, current_bidder_id, title, description, type, status, starting_price, reserved_price, current_price, drop_amount, drop_interval, last_drop_time, extend_on_bid, extend_minutes, start_time, end_time, original_end_time, created_at, updated_at
`

type UpdateAuctionStatusParams struct {
	Status AuctionStatus `json:"status"`
	ID     pgtype.UUID   `json:"id"`
}

func (q *Queries) UpdateAuctionStatus(ctx context.Context, arg UpdateAuctionStatusParams) (Auction, error) {
	row := q.db.QueryRow(ctx, updateAuctionStatus, arg.Status, arg.ID)
	var i Auction
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.CurrentBidderID,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.Status,
		&i.StartingPrice,
		&i.ReservedPrice,
		&i.CurrentPrice,
		&i.DropAmount,
		&i.DropInterval,
		&i.LastDropTime,
		&i.ExtendOnBid,
		&i.ExtendMinutes,
		&i.StartTime,
		&i.EndTime,
		&i.OriginalEndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
