// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bids.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBid = `-- name: CreateBid :one
INSERT INTO bids (
    auction_id,
    user_id,
    amount,
    is_auto_bid
)
VALUES ($1, $2, $3, $4)
RETURNING id, auction_id, user_id, amount, status, is_auto_bid, created_at, updated_at
`

type CreateBidParams struct {
	AuctionID pgtype.UUID `json:"auction_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Amount    int32       `json:"amount"`
	IsAutoBid bool        `json:"is_auto_bid"`
}

func (q *Queries) CreateBid(ctx context.Context, arg CreateBidParams) (Bid, error) {
	row := q.db.QueryRow(ctx, createBid,
		arg.AuctionID,
		arg.UserID,
		arg.Amount,
		arg.IsAutoBid,
	)
	var i Bid
	err := row.Scan(
		&i.ID,
		&i.AuctionID,
		&i.UserID,
		&i.Amount,
		&i.Status,
		&i.IsAutoBid,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveBidByUserAndAuction = `-- name: GetActiveBidByUserAndAuction :one
SELECT id, auction_id, user_id, amount, status, is_auto_bid, created_at, updated_at FROM bids
WHERE auction_id = $1
  AND user_id    = $2
  AND status     = 'Active'
LIMIT 1
`

type GetActiveBidByUserAndAuctionParams struct {
	AuctionID pgtype.UUID `json:"auction_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetActiveBidByUserAndAuction(ctx context.Context, arg GetActiveBidByUserAndAuctionParams) (Bid, error) {
	row := q.db.QueryRow(ctx, getActiveBidByUserAndAuction, arg.AuctionID, arg.UserID)
	var i Bid
	err := row.Scan(
		&i.ID,
		&i.AuctionID,
		&i.UserID,
		&i.Amount,
		&i.Status,
		&i.IsAutoBid,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBidsByAuctionID = `-- name: GetBidsByAuctionID :many
SELECT id, auction_id, user_id, amount, status, is_auto_bid, created_at, updated_at FROM bids
WHERE auction_id = $1
ORDER BY amount DESC
`

func (q *Queries) GetBidsByAuctionID(ctx context.Context, auctionID pgtype.UUID) ([]Bid, error) {
	rows, err := q.db.Query(ctx, getBidsByAuctionID, auctionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bid
	for rows.Next() {
		var i Bid
		if err := rows.Scan(
			&i.ID,
			&i.AuctionID,
			&i.UserID,
			&i.Amount,
			&i.Status,
			&i.IsAutoBid,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBidsByUserID = `-- name: GetBidsByUserID :many
SELECT id, auction_id, user_id, amount, status, is_auto_bid, created_at, updated_at FROM bids
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetBidsByUserID(ctx context.Context, userID pgtype.UUID) ([]Bid, error) {
	rows, err := q.db.Query(ctx, getBidsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bid
	for rows.Next() {
		var i Bid
		if err := rows.Scan(
			&i.ID,
			&i.AuctionID,
			&i.UserID,
			&i.Amount,
			&i.Status,
			&i.IsAutoBid,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHighestBidByAuctionID = `-- name: GetHighestBidByAuctionID :one
SELECT id, auction_id, user_id, amount, status, is_auto_bid, created_at, updated_at FROM bids
WHERE auction_id = $1
  AND status     = 'Active'
ORDER BY amount DESC
LIMIT 1
`

func (q *Queries) GetHighestBidByAuctionID(ctx context.Context, auctionID pgtype.UUID) (Bid, error) {
	row := q.db.QueryRow(ctx, getHighestBidByAuctionID, auctionID)
	var i Bid
	err := row.Scan(
		&i.ID,
		&i.AuctionID,
		&i.UserID,
		&i.Amount,
		&i.Status,
		&i.IsAutoBid,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markAllBidsRefunded = `-- name: MarkAllBidsRefunded :exec

UPDATE bids
SET
    status     = 'Refunded',
    updated_at = NOW()
WHERE auction_id = $1
  AND status     IN ('Active', 'Outbid')
`

// called when auction ends
// all outbid bids marked Lost
func (q *Queries) MarkAllBidsRefunded(ctx context.Context, auctionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markAllBidsRefunded, auctionID)
	return err
}

const markAllLosingBids = `-- name: MarkAllLosingBids :exec
UPDATE bids
SET
    status     = 'Lost',
    updated_at = NOW()
WHERE auction_id = $1
  AND status     = 'Outbid'
`

func (q *Queries) MarkAllLosingBids(ctx context.Context, auctionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markAllLosingBids, auctionID)
	return err
}

const markBidOutbid = `-- name: MarkBidOutbid :exec

UPDATE bids
SET
    status     = 'Outbid',
    updated_at = NOW()
WHERE auction_id = $1
  AND user_id    = $2
  AND status     = 'Active'
`

type MarkBidOutbidParams struct {
	AuctionID pgtype.UUID `json:"auction_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

// check if this user already has active bid
// used to detect same bidder increasing bid
func (q *Queries) MarkBidOutbid(ctx context.Context, arg MarkBidOutbidParams) error {
	_, err := q.db.Exec(ctx, markBidOutbid, arg.AuctionID, arg.UserID)
	return err
}

const markBidWon = `-- name: MarkBidWon :exec

UPDATE bids
SET
    status     = 'Won',
    updated_at = NOW()
WHERE id = $1
`

// mark previous bid as outbid
// when new higher bid comes in
func (q *Queries) MarkBidWon(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markBidWon, id)
	return err
}
