// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuctionEvent string

const (
	AuctionEventCreated                AuctionEvent = "Created"
	AuctionEventStarted                AuctionEvent = "Started"
	AuctionEventBidPlaced              AuctionEvent = "BidPlaced"
	AuctionEventBidRefunded            AuctionEvent = "BidRefunded"
	AuctionEventBidIncreased           AuctionEvent = "BidIncreased"
	AuctionEventPriceDropped           AuctionEvent = "PriceDropped"
	AuctionEventExtended               AuctionEvent = "Extended"
	AuctionEventEnded                  AuctionEvent = "Ended"
	AuctionEventCancelled              AuctionEvent = "Cancelled"
	AuctionEventWinnerDeclared         AuctionEvent = "WinnerDeclared"
	AuctionEventSellerPaid             AuctionEvent = "SellerPaid"
	AuctionEventBidderRefundedOnCancel AuctionEvent = "BidderRefundedOnCancel"
)

func (e *AuctionEvent) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuctionEvent(s)
	case string:
		*e = AuctionEvent(s)
	default:
		return fmt.Errorf("unsupported scan type for AuctionEvent: %T", src)
	}
	return nil
}

type NullAuctionEvent struct {
	AuctionEvent AuctionEvent `json:"auction_event"`
	Valid        bool         `json:"valid"` // Valid is true if AuctionEvent is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuctionEvent) Scan(value interface{}) error {
	if value == nil {
		ns.AuctionEvent, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuctionEvent.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuctionEvent) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuctionEvent), nil
}

type AuctionStatus string

const (
	AuctionStatusScheduled AuctionStatus = "Scheduled"
	AuctionStatusActive    AuctionStatus = "Active"
	AuctionStatusEnded     AuctionStatus = "Ended"
	AuctionStatusCancelled AuctionStatus = "Cancelled"
	AuctionStatusNoReserve AuctionStatus = "NoReserve"
)

func (e *AuctionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuctionStatus(s)
	case string:
		*e = AuctionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AuctionStatus: %T", src)
	}
	return nil
}

type NullAuctionStatus struct {
	AuctionStatus AuctionStatus `json:"auction_status"`
	Valid         bool          `json:"valid"` // Valid is true if AuctionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuctionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AuctionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuctionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuctionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuctionStatus), nil
}

type AuctionType string

const (
	AuctionTypeEnglish AuctionType = "English"
	AuctionTypeDutch   AuctionType = "Dutch"
)

func (e *AuctionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuctionType(s)
	case string:
		*e = AuctionType(s)
	default:
		return fmt.Errorf("unsupported scan type for AuctionType: %T", src)
	}
	return nil
}

type NullAuctionType struct {
	AuctionType AuctionType `json:"auction_type"`
	Valid       bool        `json:"valid"` // Valid is true if AuctionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuctionType) Scan(value interface{}) error {
	if value == nil {
		ns.AuctionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuctionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuctionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuctionType), nil
}

type BidStatus string

const (
	BidStatusActive   BidStatus = "Active"
	BidStatusOutbid   BidStatus = "Outbid"
	BidStatusWon      BidStatus = "Won"
	BidStatusLost     BidStatus = "Lost"
	BidStatusRefunded BidStatus = "Refunded"
)

func (e *BidStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BidStatus(s)
	case string:
		*e = BidStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BidStatus: %T", src)
	}
	return nil
}

type NullBidStatus struct {
	BidStatus BidStatus `json:"bid_status"`
	Valid     bool      `json:"valid"` // Valid is true if BidStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBidStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BidStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BidStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBidStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BidStatus), nil
}

type Auction struct {
	ID              pgtype.UUID        `json:"id"`
	SellerID        pgtype.UUID        `json:"seller_id"`
	CurrentBidderID pgtype.UUID        `json:"current_bidder_id"`
	Title           string             `json:"title"`
	Description     string             `json:"description"`
	Type            AuctionType        `json:"type"`
	Status          AuctionStatus      `json:"status"`
	StartingPrice   int32              `json:"starting_price"`
	ReservedPrice   int32              `json:"reserved_price"`
	CurrentPrice    int32              `json:"current_price"`
	DropAmount      pgtype.Int4        `json:"drop_amount"`
	DropInterval    pgtype.Int4        `json:"drop_interval"`
	LastDropTime    pgtype.Timestamptz `json:"last_drop_time"`
	ExtendOnBid     bool               `json:"extend_on_bid"`
	ExtendMinutes   int32              `json:"extend_minutes"`
	StartTime       pgtype.Timestamptz `json:"start_time"`
	EndTime         pgtype.Timestamptz `json:"end_time"`
	OriginalEndTime pgtype.Timestamptz `json:"original_end_time"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type AuctionHistory struct {
	ID        pgtype.UUID        `json:"id"`
	AuctionID pgtype.UUID        `json:"auction_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Event     AuctionEvent       `json:"event"`
	Amount    pgtype.Int4        `json:"amount"`
	Note      pgtype.Text        `json:"note"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Bid struct {
	ID        pgtype.UUID        `json:"id"`
	AuctionID pgtype.UUID        `json:"auction_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Amount    int32              `json:"amount"`
	Status    BidStatus          `json:"status"`
	IsAutoBid bool               `json:"is_auto_bid"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Otp struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Code      string             `json:"code"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Used      bool               `json:"used"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID               pgtype.UUID        `json:"id"`
	FirstName        string             `json:"first_name"`
	LastName         string             `json:"last_name"`
	Email            string             `json:"email"`
	Password         string             `json:"password"`
	AvailableBalance int32              `json:"available_balance"`
	HeldBalance      int32              `json:"held_balance"`
	IsVerified       bool               `json:"is_verified"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Winner struct {
	ID         pgtype.UUID        `json:"id"`
	AuctionID  pgtype.UUID        `json:"auction_id"`
	UserID     pgtype.UUID        `json:"user_id"`
	FinalPrice int32              `json:"final_price"`
	PaidAt     pgtype.Timestamptz `json:"paid_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}
