// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: otps.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOTP = `-- name: CreateOTP :one
INSERT INTO otps (user_id, code, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, code, expires_at, used, created_at
`

type CreateOTPParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	Code      string             `json:"code"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateOTP(ctx context.Context, arg CreateOTPParams) (Otp, error) {
	row := q.db.QueryRow(ctx, createOTP, arg.UserID, arg.Code, arg.ExpiresAt)
	var i Otp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Code,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredOTPs = `-- name: DeleteExpiredOTPs :exec
DELETE FROM otps
WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredOTPs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredOTPs)
	return err
}

const getValidOTPByUserId = `-- name: GetValidOTPByUserId :one
SELECT id, user_id, code, expires_at, used, created_at FROM otps
WHERE user_id      = $1
  AND used       = FALSE
  AND expires_at > NOW()
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetValidOTPByUserId(ctx context.Context, userID pgtype.UUID) (Otp, error) {
	row := q.db.QueryRow(ctx, getValidOTPByUserId, userID)
	var i Otp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Code,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const markOTPUsed = `-- name: MarkOTPUsed :exec
UPDATE otps
SET used = TRUE
WHERE id = $1
`

func (q *Queries) MarkOTPUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOTPUsed, id)
	return err
}
