// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// only seller can cancel their own auction
	// can only cancel before it starts
	CancelAuction(ctx context.Context, arg CancelAuctionParams) (Auction, error)
	ChangePassword(ctx context.Context, arg ChangePasswordParams) (User, error)
	// original_end_time = end_time at creation
	CreateAuction(ctx context.Context, arg CreateAuctionParams) (Auction, error)
	CreateAuctionHistory(ctx context.Context, arg CreateAuctionHistoryParams) (AuctionHistory, error)
	CreateBid(ctx context.Context, arg CreateBidParams) (Bid, error)
	CreateOTP(ctx context.Context, arg CreateOTPParams) (Otp, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWinner(ctx context.Context, arg CreateWinnerParams) (Winner, error)
	// Step 2: add to seller
	CreditAvailableBalance(ctx context.Context, arg CreditAvailableBalanceParams) (User, error)
	DeleteExpiredOTPs(ctx context.Context) error
	// user deposits money into platform
	Deposit(ctx context.Context, arg DepositParams) (User, error)
	// $1 = extend_minutes from auction row
	// safety — never drop below zero
	DropDutchPrice(ctx context.Context, id pgtype.UUID) (Auction, error)
	ExtendAuctionEndTime(ctx context.Context, arg ExtendAuctionEndTimeParams) (Auction, error)
	// always use this inside bid transaction
	// never use GetAuctionByID inside transaction
	GetActiveAuctions(ctx context.Context) ([]Auction, error)
	GetActiveBidByUserAndAuction(ctx context.Context, arg GetActiveBidByUserAndAuctionParams) (Bid, error)
	// scheduler uses this to end auctions
	GetActiveDutchAuctions(ctx context.Context) ([]Auction, error)
	GetAuctionByID(ctx context.Context, id pgtype.UUID) (Auction, error)
	GetAuctionHistory(ctx context.Context, auctionID pgtype.UUID) ([]AuctionHistory, error)
	// full timeline of everything that happened
	GetAuctionHistoryByEvent(ctx context.Context, arg GetAuctionHistoryByEventParams) ([]AuctionHistory, error)
	GetAuctionsBySellerID(ctx context.Context, sellerID pgtype.UUID) ([]Auction, error)
	GetAuctionsList(ctx context.Context, arg GetAuctionsListParams) ([]Auction, error)
	GetBidsByAuctionID(ctx context.Context, auctionID pgtype.UUID) ([]Bid, error)
	GetBidsByUserID(ctx context.Context, userID pgtype.UUID) ([]Bid, error)
	// scheduler uses this to activate auctions
	GetExpiredActiveAuctions(ctx context.Context) ([]Auction, error)
	GetHighestBidByAuctionID(ctx context.Context, auctionID pgtype.UUID) (Bid, error)
	GetScheduledAuctionsReadyToStart(ctx context.Context) ([]Auction, error)
	GetUserBidHistory(ctx context.Context, userID pgtype.UUID) ([]GetUserBidHistoryRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetValidOTPByUserId(ctx context.Context, userID pgtype.UUID) (Otp, error)
	GetWinnerByAuctionID(ctx context.Context, auctionID pgtype.UUID) (Winner, error)
	GetWinsByUserID(ctx context.Context, userID pgtype.UUID) ([]Winner, error)
	// move money from available to held
	// called when user places a new bid
	// safety check — cannot hold more than available
	HoldBidAmount(ctx context.Context, arg HoldBidAmountParams) (User, error)
	// same bidder raising their own bid
	// only charge the extra amount
	// $1 = new_amount - old_amount
	IncreaseHeldByDifference(ctx context.Context, arg IncreaseHeldByDifferenceParams) (User, error)
	LockAuctionByID(ctx context.Context, id pgtype.UUID) (Auction, error)
	LockUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	// called when auction ends
	// all outbid bids marked Lost
	MarkAllBidsRefunded(ctx context.Context, auctionID pgtype.UUID) error
	MarkAllLosingBids(ctx context.Context, auctionID pgtype.UUID) error
	// check if this user already has active bid
	// used to detect same bidder increasing bid
	MarkBidOutbid(ctx context.Context, arg MarkBidOutbidParams) error
	// mark previous bid as outbid
	// when new higher bid comes in
	MarkBidWon(ctx context.Context, id pgtype.UUID) error
	MarkOTPUsed(ctx context.Context, id pgtype.UUID) error
	MarkWinnerPaid(ctx context.Context, auctionID pgtype.UUID) error
	// move money from held back to available
	// called when user gets outbid
	ReleaseBidAmount(ctx context.Context, arg ReleaseBidAmountParams) (User, error)
	// winner's held money goes to seller available
	// two separate queries, both in same transaction
	// Step 1: remove from winner
	TransferHeldToAvailable(ctx context.Context, arg TransferHeldToAvailableParams) (User, error)
	// scheduler uses this to drop prices
	UpdateAuctionAfterBid(ctx context.Context, arg UpdateAuctionAfterBidParams) (Auction, error)
	UpdateAuctionStatus(ctx context.Context, arg UpdateAuctionStatusParams) (Auction, error)
	// use inside transaction before touching balance
	VerifyUser(ctx context.Context, email string) (User, error)
	// user withdraws money from platform
	Withdraw(ctx context.Context, arg WithdrawParams) (User, error)
}

var _ Querier = (*Queries)(nil)
