// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const changePassword = `-- name: ChangePassword :one
UPDATE users
SET
    password   = $1,
    updated_at = NOW()
WHERE id = $2
RETURNING id, first_name, last_name, email, password, available_balance, held_balance, is_verified, created_at, updated_at
`

type ChangePasswordParams struct {
	Password string      `json:"password"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) ChangePassword(ctx context.Context, arg ChangePasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, changePassword, arg.Password, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.AvailableBalance,
		&i.HeldBalance,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    first_name,
    last_name,
    email,
    password
)
VALUES ($1, $2, $3, $4)
RETURNING id, first_name, last_name, email, password, available_balance, held_balance, is_verified, created_at, updated_at
`

type CreateUserParams struct {
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Email     string `json:"email"`
	Password  string `json:"password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Password,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.AvailableBalance,
		&i.HeldBalance,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const creditAvailableBalance = `-- name: CreditAvailableBalance :one
UPDATE users
SET
    available_balance = available_balance + $1,
    updated_at        = NOW()
WHERE id = $2
RETURNING id, first_name, last_name, email, password, available_balance, held_balance, is_verified, created_at, updated_at
`

type CreditAvailableBalanceParams struct {
	AvailableBalance int32       `json:"available_balance"`
	ID               pgtype.UUID `json:"id"`
}

// Step 2: add to seller
func (q *Queries) CreditAvailableBalance(ctx context.Context, arg CreditAvailableBalanceParams) (User, error) {
	row := q.db.QueryRow(ctx, creditAvailableBalance, arg.AvailableBalance, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.AvailableBalance,
		&i.HeldBalance,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deposit = `-- name: Deposit :one
UPDATE users
SET
    available_balance = available_balance + $1,
    updated_at        = NOW()
WHERE id = $2
RETURNING id, first_name, last_name, email, password, available_balance, held_balance, is_verified, created_at, updated_at
`

type DepositParams struct {
	AvailableBalance int32       `json:"available_balance"`
	ID               pgtype.UUID `json:"id"`
}

// user deposits money into platform
func (q *Queries) Deposit(ctx context.Context, arg DepositParams) (User, error) {
	row := q.db.QueryRow(ctx, deposit, arg.AvailableBalance, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.AvailableBalance,
		&i.HeldBalance,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, first_name, last_name, email, password, available_balance, held_balance, is_verified, created_at, updated_at FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.AvailableBalance,
		&i.HeldBalance,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, first_name, last_name, email, password, available_balance, held_balance, is_verified, created_at, updated_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.AvailableBalance,
		&i.HeldBalance,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const holdBidAmount = `-- name: HoldBidAmount :one
UPDATE users
SET
    available_balance = available_balance - $1,
    held_balance      = held_balance      + $1,
    updated_at        = NOW()
WHERE id                 = $2
  AND available_balance >= $1
RETURNING id, first_name, last_name, email, password, available_balance, held_balance, is_verified, created_at, updated_at
`

type HoldBidAmountParams struct {
	AvailableBalance int32       `json:"available_balance"`
	ID               pgtype.UUID `json:"id"`
}

// move money from available to held
// called when user places a new bid
// safety check — cannot hold more than available
func (q *Queries) HoldBidAmount(ctx context.Context, arg HoldBidAmountParams) (User, error) {
	row := q.db.QueryRow(ctx, holdBidAmount, arg.AvailableBalance, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.AvailableBalance,
		&i.HeldBalance,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const increaseHeldByDifference = `-- name: IncreaseHeldByDifference :one
UPDATE users
SET
    available_balance = available_balance - $1,
    held_balance      = held_balance      + $1,
    updated_at        = NOW()
WHERE id                 = $2
  AND available_balance >= $1
RETURNING id, first_name, last_name, email, password, available_balance, held_balance, is_verified, created_at, updated_at
`

type IncreaseHeldByDifferenceParams struct {
	AvailableBalance int32       `json:"available_balance"`
	ID               pgtype.UUID `json:"id"`
}

// same bidder raising their own bid
// only charge the extra amount
// $1 = new_amount - old_amount
func (q *Queries) IncreaseHeldByDifference(ctx context.Context, arg IncreaseHeldByDifferenceParams) (User, error) {
	row := q.db.QueryRow(ctx, increaseHeldByDifference, arg.AvailableBalance, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.AvailableBalance,
		&i.HeldBalance,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockUserByID = `-- name: LockUserByID :one
SELECT id, first_name, last_name, email, password, available_balance, held_balance, is_verified, created_at, updated_at FROM users
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, lockUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.AvailableBalance,
		&i.HeldBalance,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const releaseBidAmount = `-- name: ReleaseBidAmount :one
UPDATE users
SET
    held_balance      = held_balance      - $1,
    available_balance = available_balance + $1,
    updated_at        = NOW()
WHERE id             = $2
  AND held_balance  >= $1
RETURNING id, first_name, last_name, email, password, available_balance, held_balance, is_verified, created_at, updated_at
`

type ReleaseBidAmountParams struct {
	HeldBalance int32       `json:"held_balance"`
	ID          pgtype.UUID `json:"id"`
}

// move money from held back to available
// called when user gets outbid
func (q *Queries) ReleaseBidAmount(ctx context.Context, arg ReleaseBidAmountParams) (User, error) {
	row := q.db.QueryRow(ctx, releaseBidAmount, arg.HeldBalance, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.AvailableBalance,
		&i.HeldBalance,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const transferHeldToAvailable = `-- name: TransferHeldToAvailable :one
UPDATE users
SET
    held_balance = held_balance - $1,
    updated_at   = NOW()
WHERE id            = $2
  AND held_balance >= $1
RETURNING id, first_name, last_name, email, password, available_balance, held_balance, is_verified, created_at, updated_at
`

type TransferHeldToAvailableParams struct {
	HeldBalance int32       `json:"held_balance"`
	ID          pgtype.UUID `json:"id"`
}

// winner's held money goes to seller available
// two separate queries, both in same transaction
// Step 1: remove from winner
func (q *Queries) TransferHeldToAvailable(ctx context.Context, arg TransferHeldToAvailableParams) (User, error) {
	row := q.db.QueryRow(ctx, transferHeldToAvailable, arg.HeldBalance, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.AvailableBalance,
		&i.HeldBalance,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const verifyUser = `-- name: VerifyUser :one

UPDATE users
SET
    is_verified = TRUE,
    updated_at  = NOW()
WHERE email = $1
RETURNING id, first_name, last_name, email, password, available_balance, held_balance, is_verified, created_at, updated_at
`

// use inside transaction before touching balance
func (q *Queries) VerifyUser(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, verifyUser, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.AvailableBalance,
		&i.HeldBalance,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const withdraw = `-- name: Withdraw :one
UPDATE users
SET
    available_balance = available_balance - $1,
    updated_at        = NOW()
WHERE id                 = $2
  AND available_balance >= $1
RETURNING id, first_name, last_name, email, password, available_balance, held_balance, is_verified, created_at, updated_at
`

type WithdrawParams struct {
	AvailableBalance int32       `json:"available_balance"`
	ID               pgtype.UUID `json:"id"`
}

// user withdraws money from platform
func (q *Queries) Withdraw(ctx context.Context, arg WithdrawParams) (User, error) {
	row := q.db.QueryRow(ctx, withdraw, arg.AvailableBalance, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.AvailableBalance,
		&i.HeldBalance,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
