// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: winners.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWinner = `-- name: CreateWinner :one
INSERT INTO winners (
    auction_id,
    user_id,
    final_price
)
VALUES ($1, $2, $3)
RETURNING id, auction_id, user_id, final_price, paid_at, created_at
`

type CreateWinnerParams struct {
	AuctionID  pgtype.UUID `json:"auction_id"`
	UserID     pgtype.UUID `json:"user_id"`
	FinalPrice int32       `json:"final_price"`
}

func (q *Queries) CreateWinner(ctx context.Context, arg CreateWinnerParams) (Winner, error) {
	row := q.db.QueryRow(ctx, createWinner, arg.AuctionID, arg.UserID, arg.FinalPrice)
	var i Winner
	err := row.Scan(
		&i.ID,
		&i.AuctionID,
		&i.UserID,
		&i.FinalPrice,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWinnerByAuctionID = `-- name: GetWinnerByAuctionID :one
SELECT id, auction_id, user_id, final_price, paid_at, created_at FROM winners
WHERE auction_id = $1
`

func (q *Queries) GetWinnerByAuctionID(ctx context.Context, auctionID pgtype.UUID) (Winner, error) {
	row := q.db.QueryRow(ctx, getWinnerByAuctionID, auctionID)
	var i Winner
	err := row.Scan(
		&i.ID,
		&i.AuctionID,
		&i.UserID,
		&i.FinalPrice,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWinsByUserID = `-- name: GetWinsByUserID :many
SELECT id, auction_id, user_id, final_price, paid_at, created_at FROM winners
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetWinsByUserID(ctx context.Context, userID pgtype.UUID) ([]Winner, error) {
	rows, err := q.db.Query(ctx, getWinsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Winner
	for rows.Next() {
		var i Winner
		if err := rows.Scan(
			&i.ID,
			&i.AuctionID,
			&i.UserID,
			&i.FinalPrice,
			&i.PaidAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWinnerPaid = `-- name: MarkWinnerPaid :exec
UPDATE winners
SET paid_at = NOW()
WHERE auction_id = $1
`

func (q *Queries) MarkWinnerPaid(ctx context.Context, auctionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markWinnerPaid, auctionID)
	return err
}
