/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as DashboardAuctionIndexRouteImport } from './routes/dashboard/auction/index'
import { Route as DashboardAuctionCreateRouteImport } from './routes/dashboard/auction/create'
import { Route as DashboardAuctionIdIndexRouteImport } from './routes/dashboard/auction/$id/index'
import { Route as DashboardAuctionIdEditRouteImport } from './routes/dashboard/auction/$id/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAuctionIndexRoute = DashboardAuctionIndexRouteImport.update({
  id: '/dashboard/auction/',
  path: '/dashboard/auction/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAuctionCreateRoute = DashboardAuctionCreateRouteImport.update({
  id: '/dashboard/auction/create',
  path: '/dashboard/auction/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAuctionIdIndexRoute = DashboardAuctionIdIndexRouteImport.update({
  id: '/dashboard/auction/$id/',
  path: '/dashboard/auction/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAuctionIdEditRoute = DashboardAuctionIdEditRouteImport.update({
  id: '/dashboard/auction/$id/edit',
  path: '/dashboard/auction/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/auction/create': typeof DashboardAuctionCreateRoute
  '/dashboard/auction/': typeof DashboardAuctionIndexRoute
  '/dashboard/auction/$id/edit': typeof DashboardAuctionIdEditRoute
  '/dashboard/auction/$id/': typeof DashboardAuctionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/auction/create': typeof DashboardAuctionCreateRoute
  '/dashboard/auction': typeof DashboardAuctionIndexRoute
  '/dashboard/auction/$id/edit': typeof DashboardAuctionIdEditRoute
  '/dashboard/auction/$id': typeof DashboardAuctionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/auction/create': typeof DashboardAuctionCreateRoute
  '/dashboard/auction/': typeof DashboardAuctionIndexRoute
  '/dashboard/auction/$id/edit': typeof DashboardAuctionIdEditRoute
  '/dashboard/auction/$id/': typeof DashboardAuctionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard/'
    | '/dashboard/auction/create'
    | '/dashboard/auction/'
    | '/dashboard/auction/$id/edit'
    | '/dashboard/auction/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/dashboard/auction/create'
    | '/dashboard/auction'
    | '/dashboard/auction/$id/edit'
    | '/dashboard/auction/$id'
  id:
    | '__root__'
    | '/'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/dashboard/'
    | '/dashboard/auction/create'
    | '/dashboard/auction/'
    | '/dashboard/auction/$id/edit'
    | '/dashboard/auction/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAuctionCreateRoute: typeof DashboardAuctionCreateRoute
  DashboardAuctionIndexRoute: typeof DashboardAuctionIndexRoute
  DashboardAuctionIdEditRoute: typeof DashboardAuctionIdEditRoute
  DashboardAuctionIdIndexRoute: typeof DashboardAuctionIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/auction/': {
      id: '/dashboard/auction/'
      path: '/dashboard/auction'
      fullPath: '/dashboard/auction/'
      preLoaderRoute: typeof DashboardAuctionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/auction/create': {
      id: '/dashboard/auction/create'
      path: '/dashboard/auction/create'
      fullPath: '/dashboard/auction/create'
      preLoaderRoute: typeof DashboardAuctionCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/auction/$id/': {
      id: '/dashboard/auction/$id/'
      path: '/dashboard/auction/$id'
      fullPath: '/dashboard/auction/$id/'
      preLoaderRoute: typeof DashboardAuctionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/auction/$id/edit': {
      id: '/dashboard/auction/$id/edit'
      path: '/dashboard/auction/$id/edit'
      fullPath: '/dashboard/auction/$id/edit'
      preLoaderRoute: typeof DashboardAuctionIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAuctionCreateRoute: DashboardAuctionCreateRoute,
  DashboardAuctionIndexRoute: DashboardAuctionIndexRoute,
  DashboardAuctionIdEditRoute: DashboardAuctionIdEditRoute,
  DashboardAuctionIdIndexRoute: DashboardAuctionIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
